### ISSUE TITLE
Make this available to the Typescript 2 typing system

### ISSUE THREAD

**Issue by ghost** [felixfbecker/typed-bignumber.js#2]
The new typing system for typescript 2 is super convenient. To have this .d.ts included, see the instructions at https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html.

I considered submitting a pull request to @MikeMcl that implements option #1, but unfortunately a license is specified for this .d.ts.

If you prefer option #2, the pull request to DefinitelyTyped would be simple.

Either way, getting this d.ts wired into the angular 2 type infrastructure would be greatly appreciated.

Cheers!

**Comment by felixfbecker** [comment]
I will not do the work of submitting PRs to the DT monorepo for the countless typings I maintain. It is cumbersome and impossible to "subscribe" just to these typings, and they could get out of sync with this repo. The TypeScript team promised to implement redirects to repositories in DT, until then you can use `typings` or install with NPM from GitHub.
See https://github.com/Microsoft/types-publisher/issues/4

**Comment by bgok** [comment]
I agree that this is a better approach. DefinitelyTyped is a mess.
